version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment: # variáveis de ambiente do container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports:
      - '5433:5432' #porta que recebe na máquina e porta que vai rodar
    volumes: #espelhar os dados do container em uma pasta na máquina local
      - ./data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on:
      - db

